### ISSUE TITLE
Hello! 

### ISSUE THREAD

**Issue by 459737087** [Comverser/gnlabs_converter#1]
when I run this code , it goes wrong.
**_from pypcd import pypcd_**
File "/usr/local/envs/pclpy11/lib/python3.6/site-packages/pypcd/pypcd.py", line 15, in <module>
    import cStringIO as sio
ModuleNotFoundError: No module named 'cStringIO'

**Comment by linearust** [comment]
Did you install pypcd from `https://github.com/klintan/pypcd.git`? Please, check the install instruction in the readme file.

**Comment by 459737087** [comment]
I want to convert .pcd to .bin.

**_from PIL import Image
import numpy as np
from pypcd import pypcd

def to_bin(old_file, new_file):

    pc = pypcd.PointCloud.from_path(old_file)
    np_x = (np.array(pc.pc_data["x"], dtype=np.float32)).astype(np.float32)
    np_y = (np.array(pc.pc_data["y"], dtype=np.float32)).astype(np.float32)
    np_z = (np.array(pc.pc_data["z"], dtype=np.float32)).astype(np.float32)
    np_i = (np.array(pc.pc_data["intensity"], dtype=np.float32)).astype(
        np.float32
    ) / 256

    ## Stack all data
    points_32 = np.transpose(np.vstack((np_x, np_y, np_z, np_i)))

    ## Save bin old_file
    points_32.tofile(new_file)

    
to_bin("/output/pcd/PointCloud_Color[0].pcd","/output/pcd/PointCloud_Color[0].bin")_**


but I got an error,
ValueError: no field of name intensity

@Comverser Thank u for your reply

**Comment by linearust** [comment]
The error indicates that your pcd file doesn't include `intensity` attribute.

I think deletion of `np_i` related code may solve the problem. 

Therefore, your code would be:

```py
pc = pypcd.PointCloud.from_path(old_file)
np_x = (np.array(pc.pc_data["x"], dtype=np.float32)).astype(np.float32)
np_y = (np.array(pc.pc_data["y"], dtype=np.float32)).astype(np.float32)
np_z = (np.array(pc.pc_data["z"], dtype=np.float32)).astype(np.float32)

## Stack all data
points_32 = np.transpose(np.vstack((np_x, np_y, np_z)))

## Save bin old_file
points_32.tofile(new_file)
```

**Comment by 459737087** [comment]
Thank you, it worked
@Comverser
